In [ ]:
#toddler sleeping pattern : Circadian Clocks

In [ ]:
# hypothesis testing assignment

In [ ]:
""" toddler sleeping pattern : Circadian Clocks
Parents of toddlers carefully guard and manage when and for how long their 
babies nap during the day and sleep at night. 

curious to understand.

data from the C.S. Mott Children's Hospital in Ann Arbor, Michigan 
to answer 3 burning questions:

Question 1: At what time do napping babies in the U.S. sleep at night?

Question 2: Is night bedtime for napping babies in the U.S. later than that of non-napping babies?

Question 3: Is sleep duration for napping babies in the U.S. different than 
that of non-napping babies?



hints:-

To answer Question 1, 
calculate a 95% confidence .
lower and upper confidence bounds . 

To answer Question 2, 
calculate sm.stats.ttest_ind .

To answer Question 3, 
calculate sm.stats.ttest_ind. 

find the confidence intervals 
and hypothesis tests to generate conclusions.  """

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import statsmodels.api as sm

import numpy as np
import warnings
warnings.filterwarnings("ignore")
import os
os.getcwd
pd.set_option('display.max_columns', 30)

In [ ]:
#In the variable "Napping", 1 represents nappers and 0 represents non-nappers.

In [2]:
sleep=pd.read_csv("sleep_kid.csv")

In [3]:
sleep.head()

,Unnamed: 0,Unnamed: 0.1,sex,age (months),dlmo time,days napped,napping,nap lights outl time,nap sleep onset,nap midsleep,nap sleep offset,nap wake time,nap duration,nap time in bed,night bedtime,night sleep onset,sleep onset latency,night midsleep time,night wake time,night sleep duration,night time in bed,24 h sleep duration,bedtime phase difference,sleep onset phase difference,midsleep phase difference,wake time phase difference
0,0,0,female,33.7,19.24,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.45,20.68,0.23,1.92,7.17,629.4,643.0,629.4,-1.21,-1.44,6.68,11.93
1,1,1,female,31.5,18.27,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.23,19.48,0.25,1.09,6.69,672.4,700.4,672.4,-0.96,-1.21,6.82,12.42
2,2,2,male,31.9,19.14,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.60,20.05,0.45,1.29,6.53,628.8,682.6,628.8,-0.46,-0.91,6.15,11.39
3,3,3,female,31.6,19.69,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.46,19.50,0.05,1.89,8.28,766.6,784.0,766.6,0.23,0.19,6.20,12.59
4,4,4,female,33.0,19.52,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.21,19.65,0.45,1.30,6.95,678.0,718.0,678.0,0.31,-0.13,5.78,11.43

In [4]:
sleep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    20 non-null     int64
 1   Unnamed: 0.1                  20 non-null     int64
 2   sex                           20 non-null     object
 3   age (months)                  20 non-null     float64
 4   dlmo time                     20 non-null     float64
 5   days napped                   20 non-null     int64
 6   napping                       20 non-null     int64
 7   nap lights outl time          15 non-null     float64
 8   nap sleep onset               15 non-null     float64
 9   nap midsleep                  15 non-null     float64
 10  nap sleep offset              15 non-null     float64
 11  nap wake time                 15 non-null     float64
 12  nap duration                  15 non-null     float64
 13  nap time in bed               15 non-null     float64
 14  night bedtime                 20 non-null     float64
 15  night sleep onset             20 non-null     float64
 16  sleep onset latency           20 non-null     float64
 17  night midsleep time           20 non-null     float64
 18  night wake time               20 non-null     float64
 19  night sleep duration          20 non-null     float64
 20  night time in bed             20 non-null     float64
 21  24 h sleep duration           20 non-null     float64
 22  bedtime phase difference      20 non-null     float64
 23  sleep onset phase difference  20 non-null     float64
 24  midsleep phase difference     20 non-null     float64
 25  wake time phase difference    20 non-null     float64
dtypes: float64(21), int64(4), object(1)
memory usage: 4.2+ KB

In [5]:
df=sleep.drop(["Unnamed: 0","Unnamed: 0.1"],axis=1)

In [6]:
df.head()

,sex,age (months),dlmo time,days napped,napping,nap lights outl time,nap sleep onset,nap midsleep,nap sleep offset,nap wake time,nap duration,nap time in bed,night bedtime,night sleep onset,sleep onset latency,night midsleep time,night wake time,night sleep duration,night time in bed,24 h sleep duration,bedtime phase difference,sleep onset phase difference,midsleep phase difference,wake time phase difference
0,female,33.7,19.24,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.45,20.68,0.23,1.92,7.17,629.4,643.0,629.4,-1.21,-1.44,6.68,11.93
1,female,31.5,18.27,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.23,19.48,0.25,1.09,6.69,672.4,700.4,672.4,-0.96,-1.21,6.82,12.42
2,male,31.9,19.14,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.60,20.05,0.45,1.29,6.53,628.8,682.6,628.8,-0.46,-0.91,6.15,11.39
3,female,31.6,19.69,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.46,19.50,0.05,1.89,8.28,766.6,784.0,766.6,0.23,0.19,6.20,12.59
4,female,33.0,19.52,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.21,19.65,0.45,1.30,6.95,678.0,718.0,678.0,0.31,-0.13,5.78,11.43

In [7]:
df.shape

(20, 24)

In [9]:
# Create dataframes for bedtimes for nappers and non-nappers
nap_bedtime = df[df.napping == 1]
no_nap_bedtime = df[df.napping == 0]

In [10]:
nap_bedtime.head()

,sex,age (months),dlmo time,days napped,napping,nap lights outl time,nap sleep onset,nap midsleep,nap sleep offset,nap wake time,nap duration,nap time in bed,night bedtime,night sleep onset,sleep onset latency,night midsleep time,night wake time,night sleep duration,night time in bed,24 h sleep duration,bedtime phase difference,sleep onset phase difference,midsleep phase difference,wake time phase difference
5,female,36.2,18.22,4,1,14.00,14.22,15.00,15.78,16.28,93.75,137.00,19.95,20.25,0.29,1.26,6.28,602.2,653.80,695.95,-1.73,-2.03,7.05,12.06
6,male,36.3,19.28,1,1,14.75,15.03,15.92,16.80,16.08,106.00,80.00,20.60,20.96,0.36,2.12,7.27,618.4,655.40,724.40,-1.32,-1.68,6.84,11.99
7,male,30.0,21.06,5,1,13.09,13.43,14.44,15.46,15.82,121.60,163.80,22.01,22.53,0.51,2.92,7.31,526.8,582.40,648.40,-0.95,-1.47,5.86,10.25
8,male,33.2,19.38,2,1,14.41,14.42,15.71,17.01,16.60,155.50,131.25,20.24,20.37,0.13,1.60,6.82,626.8,660.33,782.30,-0.86,-0.99,6.22,11.44
9,female,37.1,19.93,3,1,13.12,13.42,14.31,15.19,15.30,106.67,130.67,20.78,21.63,0.84,2.20,6.52,549.5,626.00,656.17,-0.76,-1.82,6.21,10.59

In [13]:
nap_bedtime.shape

(15, 24)

In [11]:
no_nap_bedtime.head()

,sex,age (months),dlmo time,days napped,napping,nap lights outl time,nap sleep onset,nap midsleep,nap sleep offset,nap wake time,nap duration,nap time in bed,night bedtime,night sleep onset,sleep onset latency,night midsleep time,night wake time,night sleep duration,night time in bed,24 h sleep duration,bedtime phase difference,sleep onset phase difference,midsleep phase difference,wake time phase difference
0,female,33.7,19.24,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.45,20.68,0.23,1.92,7.17,629.4,643.0,629.4,-1.21,-1.44,6.68,11.93
1,female,31.5,18.27,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.23,19.48,0.25,1.09,6.69,672.4,700.4,672.4,-0.96,-1.21,6.82,12.42
2,male,31.9,19.14,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.60,20.05,0.45,1.29,6.53,628.8,682.6,628.8,-0.46,-0.91,6.15,11.39
3,female,31.6,19.69,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.46,19.50,0.05,1.89,8.28,766.6,784.0,766.6,0.23,0.19,6.20,12.59
4,female,33.0,19.52,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.21,19.65,0.45,1.30,6.95,678.0,718.0,678.0,0.31,-0.13,5.78,11.43

In [14]:
no_nap_bedtime.shape

(5, 24)

In [ ]:
Question 1: At what time do napping babies in the U.S. sleep at night?
hint :- use the column ["night bedtime"]

##### Question 2: Is night bedtime for napping babies in the U.S. later than that of non-napping babies?

In [9]:
 #hint :- # Mean night bedtime for nappers and non_nappers

##### Q3: Is sleep duration for napping babies in the U.S. different than that of non-napping babies?

In [ ]:
hint :- use the column
    ["night sleep duration"]